//
//  MockData.swift
//  FinHub-SwiftUI
//
//  
//

import Foundation
import AVFoundation

struct MockData {
    var stories: [Story] = [
        Story(user: User(userName: "Abduallah", userImage: "user_1"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: "Lele", userImage: "maryam"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: "Sam", userImage: "expert1"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: "Raj", userImage: "user_4"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: "Karmela", userImage: "user_5"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: "Daived", userImage: "user_6"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: "Nasser", userImage: "user_7"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: "cristiano", userImage: "user_8"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: "zendaya", userImage: "user_9"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: "Billie", userImage: "user_10"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: "Alfredo", userImage: "user_11"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: "Zahrah", userImage: "user_12"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: "Salman", userImage: "user_13"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: "sergioramos", userImage: "manar"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: "Andy", userImage: "user_15"),
              hasSeen: false,
              isMyStory: false),
        Story(user: User(userName: " Sarah", userImage: "user_16"),
              hasSeen: false,
              isMyStory: false)
    ]
    
    var posts: [Post] = [
        Post(user: User(userName: "Sarah", userImage: "user_16"),
             postImage: "post_1",
             caption:"Control Your Financial Future If you don’t learn to manage your money, then other people will find ways to mismanage it for you.Some of these people may be ill-intentioned, like unscrupulous, commission-based financial planners. Others may be well-meaning but may not know what they’re doing, like Grandma Betty, who really wants you to own your own house even though you can only afford one by taking on a risky adjustable-rate mortgage",


            
             likes: "leomessi and others liked"),
        Post(user: User(userName: "Andy", userImage: "user_15"),
             postImage: "post_2",
             caption: "Control Your Financial Future If you don’t learn to manage your money, then other people will find ways to mismanage it for you.Some of these people may be ill-intentioned, like unscrupulous, commission-based financial planners. Others may be well-meaning but may not know what they’re doing, like Grandma Betty, who really wants you to own your own house even though you can only afford one by taking on a risky adjustable-rate mortgage",
             likes: "waynerooney and others liked"),
        Post(user: User(userName: "sergioramos", userImage: "manar"),
             postImage: "post_3",
             caption: "Control Your Financial Future If you don’t learn to manage your money, then other people will find ways to mismanage it for you.Some of these people may be ill-intentioned, like unscrupulous, commission-based financial planners. Others may be well-meaning but may not know what they’re doing, like Grandma Betty, who really wants you to own your own house even though you can only afford one by taking on a risky adjustable-rate mortgage",
             likes: "leomessi and others liked"),
      
        Post(user: User(userName: "Zahrah", userImage: "Abdullah2"),
             postImage: "post_5",
             caption: "Control Your Financial Future If you don’t learn to manage your money, then other people will find ways to mismanage it for you.Some of these people may be ill-intentioned, like unscrupulous, commission-based financial planners. Others may be well-meaning but may not know what they’re doing, like Grandma Betty, who really wants you to own your own house even though you can only afford one by taking on a risky adjustable-rate mortgage",
             likes: "sherlock and others liked"),
        Post(user: User(userName: "Alfredo", userImage: "Abdullah1"),
             postImage: "post_6",
             caption: "Control Your Financial Future If you don’t learn to manage your money, then other people will find ways to mismanage it for you.Some of these people may be ill-intentioned, like unscrupulous, commission-based financial planners. Others may be well-meaning but may not know what they’re doing, like Grandma Betty, who really wants you to own your own house even though you can only afford one by taking on a risky adjustable-rate mortgage",
             likes: "john_watson and others liked"),
        Post(user: User(userName: "Billie", userImage: "Abdullah0"),
             postImage: "post_7",
             caption: "Control Your Financial Future If you don’t learn to manage your money, then other people will find ways to mismanage it for you.Some of these people may be ill-intentioned, like unscrupulous, commission-based financial planners. Others may be well-meaning but may not know what they’re doing, like Grandma Betty, who really wants you to own your own house even though you can only afford one by taking on a risky adjustable-rate mortgage",
             likes: "tommyshelby and others liked"),
        Post(user: User(userName: "zendaya", userImage: "user_9"),
             postImage: "post_8",
             caption: "Control Your Financial Future If you don’t learn to manage your money, then other people will find ways to mismanage it for you.Some of these people may be ill-intentioned, like unscrupulous, commission-based financial planners. Others may be well-meaning but may not know what they’re doing, like Grandma Betty, who really wants you to own your own house even though you can only afford one by taking on a risky adjustable-rate mortgage",
             likes: "leomessi and others liked"),
        Post(user: User(userName: "cristiano", userImage: "user_8"),
             postImage: "post_9",
             caption:"Control Your Financial Future If you don’t learn to manage your money, then other people will find ways to mismanage it for you.Some of these people may be ill-intentioned, like unscrupulous, commission-based financial planners. Others may be well-meaning but may not know what they’re doing, like Grandma Betty, who really wants you to own your own house even though you can only afford one by taking on a risky adjustable-rate mortgage",
             likes: "ronaldo and others liked"),
        Post(user: User(userName: "Nasser", userImage: "user_7"),
             postImage: "post_10",
             caption: "Control Your Financial Future If you don’t learn to manage your money, then other people will find ways to mismanage it for you.Some of these people may be ill-intentioned, like unscrupulous, commission-based financial planners. Others may be well-meaning but may not know what they’re doing, like Grandma Betty, who really wants you to own your own house even though you can only afford one by taking on a risky adjustable-rate mortgage",
             likes: "pele and others liked"),
        Post(user: User(userName: "leen", userImage: "Abdullah6"),
             postImage: "post_19",
             caption: "Control Your Financial Future If you don’t learn to manage your money, then other people will find ways to mismanage it for you.Some of these people may be ill-intentioned, like unscrupulous, commission-based financial planners. Others may be well-meaning but may not know what they’re doing, like Grandma Betty, who really wants you to own your own house even though you can only afford one by taking on a risky adjustable-rate mortgage",
             likes: "leomessi and others liked"),
        Post(user: User(userName: "Daived", userImage: "user_6"),
             postImage: "post_11",
             caption: "Control Your Financial Future If you don’t learn to manage your money, then other people will find ways to mismanage it for you.Some of these people may be ill-intentioned, like unscrupulous, commission-based financial planners. Others may be well-meaning but may not know what they’re doing, like Grandma Betty, who really wants you to own your own house even though you can only afford one by taking on a risky adjustable-rate mortgage",
             likes: "pankaj and others liked"),
        Post(user: User(userName: "Karmela", userImage: "user_5"),
             postImage: "post_12",
             caption: "Control Your Financial Future If you don’t learn to manage your money, then other people will find ways to mismanage it for you.Some of these people may be ill-intentioned, like unscrupulous, commission-based financial planners. Others may be well-meaning but may not know what they’re doing, like Grandma Betty, who really wants you to own your own house even though you can only afford one by taking on a risky adjustable-rate mortgage",
             likes: "vardy7 and others liked"),
        Post(user: User(userName: "Raj", userImage: "user_4"),
             postImage: "post_13",
             caption:"Control Your Financial Future If you don’t learn to manage your money, then other people will find ways to mismanage it for you.Some of these people may be ill-intentioned, like unscrupulous, commission-based financial planners. Others may be well-meaning but may not know what they’re doing, like Grandma Betty, who really wants you to own your own house even though you can only afford one by taking on a risky adjustable-rate mortgage",
             likes: "leomessi and others liked"),
        Post(user: User(userName: "Sam", userImage: "expert1"),
             postImage: "post_14",
             caption: "Control Your Financial Future If you don’t learn to manage your money, then other people will find ways to mismanage it for you.Some of these people may be ill-intentioned, like unscrupulous, commission-based financial planners. Others may be well-meaning but may not know what they’re doing, like Grandma Betty, who really wants you to own your own house even though you can only afford one by taking on a risky adjustable-rate mortgage", likes: "frenkydejong and others liked"),
        Post(user: User(userName: "Lele", userImage: "maryam"),
             postImage: "post_15",
             caption: "The leader teaches more through being than through doing. The quality of one's silence conveys more than long speeches.",
             likes: "leomessi and others liked"),
        Post(user: User(userName: "leen", userImage: "Abdullah6"),
             postImage: "post_16",
             caption: "Be so true to thyself as thou be not false to others.",
             likes: "luisenrique and others liked"),
        Post(user: User(userName: "    Abduallah", userImage: "Abdullah"),
             postImage: "post_17",
             caption: "The best reply to an atheist is to give him a good dinner and ask him if he believes there is a cook.",
             likes: "bhaichung and others liked"),
     
    ]
    
    var activity: [Activity] = [
        Activity(activity: .liked,
                 duration: "15m",
                 usersInContext: [User(userName: "christy", userImage: "Lucy"), User(userName: "Ahmed", userImage: "ahmed")],
                 post: Post(user: User(userName: "peter", userImage: "expert3"), postImage: "post_18", caption: "Thank you for the help.", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "Nasser", userImage: "expert1")],
                 post: Post(user: User(userName: "Dalal", userImage: "expert6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "5h",
                 usersInContext: [User(userName: "Lele", userImage: "maryam"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .comment,
                 duration: "5h",
                 usersInContext: [User(userName: "zendaya", userImage: "expert8")],
                 post: Post(user: User(userName: "jimmie", userImage: "expert3"), postImage: "post_18", caption: "Today's advice", likes: "leomessi and others liked"),
                 comment: "@ahmed ❤️🙏🏻"),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "abdu", userImage: "Abdullah7")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "    Abduallah", userImage: "Abdullah"), User(userName: "Lele", userImage: "maryam") ],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "sherlock", userImage: "malak"), User(userName: "john_watson", userImage: "user_8") ],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "hiker.benn", userImage: "maryam")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .newFollower,
                 duration: "8h",
                 usersInContext: [User(userName: "abasu63", userImage: "Abdullah9")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "harry_potter", userImage: "user_9"), User(userName: "john_wisley", userImage: "Abdullah6") ],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "salem", userImage: "malak")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "15m",
                 usersInContext: [User(userName: "cristiano", userImage: "user_8"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "rock'n_roll", userImage: "manar")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "5h",
                 usersInContext: [User(userName: "Lele", userImage: "maryam"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .comment,
                 duration: "5h",
                 usersInContext: [User(userName: "zendaya", userImage: "user_9")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: "@leen ❤️🙏🏻"),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "abdu", userImage: "Abdullah7")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "    Abduallah", userImage: "Abdullah"), User(userName: "Lele", userImage: "maryam") ],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "sherlock", userImage: "malak"), User(userName: "john_watson", userImage: "user_8") ],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "hiker.benn", userImage: "maryam")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .newFollower,
                 duration: "8h",
                 usersInContext: [User(userName: "abasu63", userImage: "Abdullah9")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "harry_potter", userImage: "user_9"), User(userName: "john_wisley", userImage: "Abdullah6") ],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "salem", userImage: "malak")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "15m",
                 usersInContext: [User(userName: "cristiano", userImage: "user_8"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "rock'n_roll", userImage: "manar")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "5h",
                 usersInContext: [User(userName: "Lele", userImage: "maryam"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .comment,
                 duration: "5h",
                 usersInContext: [User(userName: "zendaya", userImage: "user_9")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: "@leen ❤️🙏🏻"),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "abdu", userImage: "Abdullah7")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "    Abduallah", userImage: "Abdullah"), User(userName: "Lele", userImage: "maryam") ],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "sherlock", userImage: "malak"), User(userName: "john_watson", userImage: "user_8") ],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "hiker.benn", userImage: "maryam")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .newFollower,
                 duration: "8h",
                 usersInContext: [User(userName: "abasu63", userImage: "Abdullah9")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "harry_potter", userImage: "user_9"), User(userName: "john_wisley", userImage: "Abdullah6") ],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "salem", userImage: "malak")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "15m",
                 usersInContext: [User(userName: "cristiano", userImage: "user_8"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "rock'n_roll", userImage: "manar")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "5h",
                 usersInContext: [User(userName: "Lele", userImage: "maryam"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .comment,
                 duration: "5h",
                 usersInContext: [User(userName: "zendaya", userImage: "user_9")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: "@leen ❤️🙏🏻"),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "abdu", userImage: "Abdullah7")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "    Abduallah", userImage: "Abdullah"), User(userName: "Lele", userImage: "maryam") ],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "sherlock", userImage: "malak"), User(userName: "john_watson", userImage: "user_8") ],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "hiker.benn", userImage: "maryam")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .newFollower,
                 duration: "8h",
                 usersInContext: [User(userName: "abasu63", userImage: "Abdullah9")],
                 post: Post(user: User(userName: "leen", userImage: "Abdullah6"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "harry_potter", userImage: "user_9"), User(userName: "john_wisley", userImage: "z6") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "salem", userImage: "malak")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "15m",
                 usersInContext: [User(userName: "cristiano", userImage: "user_8"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "rock'n_roll", userImage: "manar")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "5h",
                 usersInContext: [User(userName: "Lele", userImage: "maryam"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .comment,
                 duration: "5h",
                 usersInContext: [User(userName: "zendaya", userImage: "user_9")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: "@leen ❤️🙏🏻"),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "abdu", userImage: "user_17")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "    Abduallah", userImage: "user_1"), User(userName: "Lele", userImage: "maryam") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "sherlock", userImage: "malak"), User(userName: "john_watson", userImage: "user_8") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "hiker.benn", userImage: "maryam")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .newFollower,
                 duration: "8h",
                 usersInContext: [User(userName: "abasu63", userImage: "user_19")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "harry_potter", userImage: "user_9"), User(userName: "john_wisley", userImage: "user_16") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "salem", userImage: "malak")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "15m",
                 usersInContext: [User(userName: "cristiano", userImage: "user_8"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "rock'n_roll", userImage: "manar")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "5h",
                 usersInContext: [User(userName: "Lele", userImage: "maryam"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .comment,
                 duration: "5h",
                 usersInContext: [User(userName: "zendaya", userImage: "user_9")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: "@leen ❤️🙏🏻"),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "abdu", userImage: "user_17")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "    Abduallah", userImage: "user_1"), User(userName: "Lele", userImage: "maryam") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "sherlock", userImage: "malak"), User(userName: "john_watson", userImage: "user_8") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "hiker.benn", userImage: "maryam")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .newFollower,
                 duration: "8h",
                 usersInContext: [User(userName: "abasu63", userImage: "user_19")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "harry_potter", userImage: "user_9"), User(userName: "john_wisley", userImage: "user_16") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "salem", userImage: "malak")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "15m",
                 usersInContext: [User(userName: "cristiano", userImage: "user_8"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "rock'n_roll", userImage: "manar")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "5h",
                 usersInContext: [User(userName: "Lele", userImage: "maryam"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .comment,
                 duration: "5h",
                 usersInContext: [User(userName: "zendaya", userImage: "user_9")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: "@leen ❤️🙏🏻"),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "abdu", userImage: "user_17")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "    Abduallah", userImage: "user_1"), User(userName: "Lele", userImage: "maryam") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "sherlock", userImage: "malak"), User(userName: "john_watson", userImage: "user_8") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "hiker.benn", userImage: "maryam")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .newFollower,
                 duration: "8h",
                 usersInContext: [User(userName: "abasu63", userImage: "user_19")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "harry_potter", userImage: "user_9"), User(userName: "john_wisley", userImage: "user_16") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "salem", userImage: "malak")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "15m",
                 usersInContext: [User(userName: "cristiano", userImage: "user_8"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "rock'n_roll", userImage: "manar")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "5h",
                 usersInContext: [User(userName: "Lele", userImage: "maryam"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .comment,
                 duration: "5h",
                 usersInContext: [User(userName: "zendaya", userImage: "user_9")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: "@leen ❤️🙏🏻"),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "abdu", userImage: "user_17")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "    Abduallah", userImage: "user_1"), User(userName: "Lele", userImage: "maryam") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "sherlock", userImage: "malak"), User(userName: "john_watson", userImage: "user_8") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "hiker.benn", userImage: "maryam")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .newFollower,
                 duration: "8h",
                 usersInContext: [User(userName: "abasu63", userImage: "user_19")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "harry_potter", userImage: "user_9"), User(userName: "john_wisley", userImage: "user_16") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "salem", userImage: "malak")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "15m",
                 usersInContext: [User(userName: "cristiano", userImage: "user_8"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "rock'n_roll", userImage: "manar")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "5h",
                 usersInContext: [User(userName: "Lele", userImage: "maryam"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .comment,
                 duration: "5h",
                 usersInContext: [User(userName: "zendaya", userImage: "user_9")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: "@leen ❤️🙏🏻"),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "abdu", userImage: "user_17")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "    Abduallah", userImage: "user_1"), User(userName: "Lele", userImage: "maryam") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "sherlock", userImage: "malak"), User(userName: "john_watson", userImage: "user_8") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "hiker.benn", userImage: "maryam")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .newFollower,
                 duration: "8h",
                 usersInContext: [User(userName: "abasu63", userImage: "user_19")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "harry_potter", userImage: "user_9"), User(userName: "john_wisley", userImage: "user_16") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "salem", userImage: "malak")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "15m",
                 usersInContext: [User(userName: "cristiano", userImage: "user_8"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "rock'n_roll", userImage: "manar")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "5h",
                 usersInContext: [User(userName: "Lele", userImage: "maryam"), User(userName: "Nasser", userImage: "user_7")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .comment,
                 duration: "5h",
                 usersInContext: [User(userName: "zendaya", userImage: "user_9")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: "@leen ❤️🙏🏻"),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "abdu", userImage: "user_17")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "    Abduallah", userImage: "user_1"), User(userName: "Lele", userImage: "maryam") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "sherlock", userImage: "malak"), User(userName: "john_watson", userImage: "user_8") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .suggestFollower,
                 duration: "6h",
                 usersInContext: [User(userName: "hiker.benn", userImage: "maryam")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .newFollower,
                 duration: "8h",
                 usersInContext: [User(userName: "abasu63", userImage: "user_19")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
        Activity(activity: .liked,
                 duration: "46m",
                 usersInContext: [User(userName: "harry_potter", userImage: "user_9"), User(userName: "john_wisley", userImage: "user_16") ],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked")),
        Activity(activity: .newFollower,
                 duration: "18h",
                 usersInContext: [User(userName: "salem", userImage: "malak")],
                 post: Post(user: User(userName: "leen", userImage: "user_16"), postImage: "post_18", caption: "..", likes: "leomessi and others liked"),
                 comment: ""),
    ]
    
 
}


